CREATE TABLE IF NOT EXISTS users(
id int (12) UNSIGNED NOT NULL UNIQUE,
firstname varchar(255) CHARACTER SET utf8,
lastname varchar(255) CHARACTER SET utf8,
creation_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);
